# Generated by Django 3.2.8 on 2021-10-23 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('people_impact', models.TextField()),
                ('legislative_scope', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=25)),
                ('donors', models.ManyToManyField(related_name='donors', to=settings.AUTH_USER_MODEL)),
                ('organizers', models.ManyToManyField(related_name='organizers', to=settings.AUTH_USER_MODEL)),
                ('primary_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_organizer', to=settings.AUTH_USER_MODEL)),
                ('sponsors', models.ManyToManyField(related_name='sponsors', to=settings.AUTH_USER_MODEL)),
                ('supporters', models.ManyToManyField(related_name='supporters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField()),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initz.initiative')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initz.initiative')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dt', models.DateTimeField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('attendees', models.ManyToManyField(related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initz.initiative')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initz.initiative')),
            ],
        ),
    ]
