# Generated by Django 3.2.8 on 2021-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='No Expense Title Set', max_length=200),
        ),
    ]
