# Generated by Django 3.2.8 on 2021-10-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initz', '0004_auto_20211023_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initz.initiative'),
        ),
    ]
